branch-defaults:
  main:
    environment: Files-env
environment-defaults:
  Files-env:
    branch: null
    repository: null
global:
  application_name: 'Files '
  default_ec2_keyname: null
  default_platform: Python 3.8 running on 64bit Amazon Linux 2
  default_region: us-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
deploy:
  artifact: deployment.zip